"""user table 수정

Revision ID: d0822d713044
Revises: c15ab774b60a
Create Date: 2025-01-06 20:18:33.419542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0822d713044'
down_revision: Union[str, None] = 'c15ab774b60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
